name: Deploy Database Schemas
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'liquibase/**'
      - '.github/workflows/deployDatabase.yml'

env:
  DB_SERVER: "${{ secrets.AZURE_SQL_SERVER }}.database.windows.net"
  DB_USER: "${{ secrets.SQL_USER }}"
  DB_PASSWORD: "${{ secrets.SQL_PASS }}"

jobs:
  deploy-dimensional-models:
    name: Deploy Dimensional Models
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          - { folder: 'modelo01', db_name: 'dw_envios', sql_file: 'modelo01_envios.sql' }
          - { folder: 'modelo02', db_name: 'dw_reservas_viaje', sql_file: 'modelo02_reservas.sql' }
          - { folder: 'modelo03', db_name: 'dw_gestion_proyectos', sql_file: 'modelo03_proyectos.sql' }
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Liquibase
        run: |
          # Instalar Liquibase
          wget https://github.com/liquibase/liquibase/releases/download/v4.27.0/liquibase-4.27.0.tar.gz -O /tmp/liquibase.tar.gz
          sudo mkdir -p /opt/liquibase
          sudo tar -xzf /tmp/liquibase.tar.gz -C /opt/liquibase
          sudo ln -s /opt/liquibase/liquibase /usr/local/bin/liquibase
          
          # Instalar driver JDBC
          wget https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.2.jre11/mssql-jdbc-12.4.2.jre11.jar -O /tmp/sqljdbc.jar
          echo "LIQUIBASE_CLASSPATH=/tmp/sqljdbc.jar" >> $GITHUB_ENV

      - name: Test database connection
        run: |
          # Verificación básica de conexión sin Liquibase
          echo "Testing connection to ${{ matrix.model.db_name }}..."
          curl --connect-timeout 5 telnet://${{ env.DB_SERVER }}:1433 || echo "Connection test failed"

      - name: Apply database changes
        run: |
          liquibase \
            --url="jdbc:sqlserver://${{ env.DB_SERVER }}:1433;database=${{ matrix.model.db_name }};encrypt=true;trustServerCertificate=true" \
            --username="${{ env.DB_USER }}" \
            --password="${{ env.DB_PASSWORD }}" \
            --driver="com.microsoft.sqlserver.jdbc.SQLServerDriver" \
            --classpath="${{ env.LIQUIBASE_CLASSPATH }}" \
            --changeLogFile="liquibase/changelog/${{ matrix.model.folder }}/changelog-master.xml" \
            --logLevel=info \
            update
