name: Deploy to Shorten Database
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'liquibase/**'
      - '.github/workflows/deployDatabase.yml'

env:
  DB_SERVER: "${{ secrets.AZURE_SQL_SERVER }}.database.windows.net"
  DB_USER: "${{ secrets.SQL_USER }}"
  DB_PASSWORD: "${{ secrets.SQL_PASS }}"
  LIQUIBASE_CLASSPATH: /tmp/sqljdbc.jar

jobs:
  deploy-to-shorten:
    name: Deploy to Shorten DB
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SQL Server tools
        run: |
          # Configurar repositorio Microsoft
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          
          # Instalar sqlcmd y dependencias
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc
          
          # Verificar instalación
          sqlcmd -?

      - name: Install Liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.27.0/liquibase-4.27.0.tar.gz -O /tmp/liquibase.tar.gz
          sudo mkdir -p /opt/liquibase
          sudo tar -xzf /tmp/liquibase.tar.gz -C /opt/liquibase
          sudo ln -s /opt/liquibase/liquibase /usr/local/bin/liquibase
          wget https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.2.jre11/mssql-jdbc-12.4.2.jre11.jar -O $LIQUIBASE_CLASSPATH

      - name: Verify database connection
        run: |
          # Esperar 10 segundos para asegurar que las herramientas están disponibles
          sleep 10
          
          echo "Probando conexión al servidor..."
          if ! sqlcmd -S "$DB_SERVER" -U "$DB_USER" -P "$DB_PASSWORD" -Q "SELECT @@VERSION"; then
            echo "::error::No se pudo conectar al servidor SQL"
            exit 1
          fi
          
          echo "Verificando base de datos 'shorten'..."
          if sqlcmd -S "$DB_SERVER" -U "$DB_USER" -P "$DB_PASSWORD" -Q "SELECT name FROM master.sys.databases WHERE name = 'shorten'" | grep -q "shorten"; then
            echo "Base de datos 'shorten' existe"
          else
            echo "::error::La base de datos 'shorten' no existe o no se puede acceder"
            exit 1
          fi

      - name: Run Liquibase migration
        run: |
          liquibase \
            --url="jdbc:sqlserver://$DB_SERVER:1433;database=shorten;encrypt=true;trustServerCertificate=true" \
            --username="$DB_USER" \
            --password="$DB_PASSWORD" \
            --driver="com.microsoft.sqlserver.jdbc.SQLServerDriver" \
            --classpath="$LIQUIBASE_CLASSPATH" \
            --changeLogFile="liquibase/changelog/modelo01/changelog-master.xml" \
            --logLevel=debug \
            update
